//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DODY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Sno { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public Nullable<int> Order_Count { get; set; }
        public Nullable<int> Sold { get; set; }
        public Nullable<int> Canceled { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> Ono { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
